services:
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: entrelinhas-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - entrelinhas-network

networks:
  entrelinhas-network:
    driver: bridge